name: Decrypt App Keys

on:
  workflow_dispatch:

env:
  DEPLOYMENT_NAME: Decrypt App Keys
  key: ${{ secrets.key }}
  token: "${{ secrets.GIT_TOKEN }}"

jobs:
  apigee-window-artifacts:
    name: Decrypt App Keys
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Check out Git repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GIT_TOKEN }}"

      - name: Decrypt App Keys
        shell: pwsh
        run: |
          $env:ORG = "${{ secrets.APIGEE_ORG }}"
          $env:key = "${{ secrets.key }}"
          $env:token: "${{ secrets.GIT_TOKEN }}"
          Invoke-Pester ./decrypt-app-keys.ps1 -Passthru


