name: AES Encrypt Plain Text

on:
  workflow_dispatch:

env:
  DEPLOYMENT_NAME: AES Encrypt Plain Text
  key: ${{ secrets.key }}
  staticparam: "Hello Pavan..!"

jobs:
  AES-Encrypt-Plain-Text:
    name: AES Encrypt Plain Text
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Check out Git repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GIT_TOKEN }}"

      - name: AES Encrypt Plain Text
        shell: pwsh
        run: |
          $env:key = "${{ secrets.key }}"
          $env:value = $env:staticparam

          $env:targetgithubUsername = "pavansirasanambedu"
          $env:targetrepositoryName = "common-encrypt-decrypt"
          $env:targetBranchName = "encrypt/plaintext" 
          $env:targetFilePath = "encrypt/encrypt-plaintext.json"

          Invoke-Pester ./encrypt-staticparameter.ps1 -Passthru
