name: Encrypt json file data

on:
  workflow_dispatch:

env:
  DEPLOYMENT_NAME: Encrypt json file data # TODO: update to deployment name
  key: ${{ secrets.key }}

jobs:
  apigee-window-artifacts:
    name: Encrypt json file data
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Set Git identity
        run: |
          git config --global user.email "rajeshjanapati533@gmail.com"
          git config --global user.name "pavansirasanambedu"

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Encrypt json file data
        shell: pwsh
        run: |
          $env:token = "${{ secrets.GIT_TOKEN }}"
          $env:key = "${{ secrets.key }}"

          $env:sourcegithubUsername = "pavansirasanambedu"
          $env:sourcerepositoryName = "common-encrypt-decrypt"
          $env:sourcebranchName = "encrypt/jsonfile"
          $env:sourcefilePath = "jsonfile/appdata.json"

          $env:targetgithubUsername = "pavansirasanambedu"
          $env:targetrepositoryName = "common-encrypt-decrypt"
          $env:targetBranchName = "encrypt/jsonfile" 
          $env:targetFilePath = "encrypt-jsonfile/encrypt-jsondata.json" 
          
    
          Invoke-Pester ./encrypt-json-file.ps1 -Passthru

      # - name: Debug Git Config
      #   run: |
      #     git config --list

      # - name: Add local files to Git local branch
      #   run: |
      #       git config --global user.email "rajeshjanapati533@gmail.com"
      #       git config --global user.name "pavansirasanambedu"
      #       git add .

      # - name: Check for delta changes - Git
      #   id: check_git_changes
      #   run: |
      #     if [[ -n "$(git status --porcelain)" ]]; then
      #       echo "Local branch is not up to date with remote_branch. Pushing latest code to Git"
      #     else
      #       echo "Local branch is up to date with Remote branch."
      #       exit 0
      #     fi

      # - name: Commit files to Git
      #   run: |
      #     if [[ -n "$(git status --porcelain)" ]]; then
      #       git commit -a -m "Apigee Artifacts Export Updates"
      #       exit 0
      #     fi

      # - name: Debug Git Status
      #   run: |
      #     git status

      # - name: Push changes to Git
      #   run: |
      #     git push origin encrypt/jsonfile
