name: PowerShell Script Example

on: push

jobs:
  run-powershell-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set execute permission for scripts.ps1
      run: chmod +x variable-call.ps1

    - name: Run PowerShell script
      shell: /usr/bin/pwsh -command ". '{0}'"
      run: |
        # Execute the PowerShell script and store its output in a variable
        OUTPUT_FROM_SCRIPT=$(./variable-call.ps1)

        # Print the output to the workflow log
        echo "Variable value: $OUTPUT_FROM_SCRIPT"
