name: Example Workflow

on: push

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PowerShell script
        id: run_script
        shell: pwsh
        run: |
          # Run your PowerShell script and capture the output
          $output = ./scripts.ps1
          echo "::set-output name=my_output::$output"

      - name: Print Captured Output
        run: |
          # Access the captured output variable and print it
          captured_output="${{ steps.run_script.outputs.my_output }}"
          echo "Captured Output: $captured_output"
